### ISSUE TITLE
attempt to index a string value (field 'info')

### ISSUE THREAD

**Issue by ghost** [helenclarko/qb-itemstorage#1]
when I try to access the item
```
[script:qb-itemstorag] SCRIPT ERROR: @qb-itemstorage/server/main.lua:23: attempt to index a string value (field 'info')
[script:qb-itemstorag] > TriggerCallback (@qb-core/server/functions.lua:207)
[script:qb-itemstorag] > handler (@qb-core/server/events.lua:110)
[      script:qb-core] SCRIPT ERROR: error object is not a string
[      script:qb-core] (nil stack trace)
```

**Comment by helenclarko** [comment]
Which inventory script are you using?

**Comment by ghost** [comment]
lj-inventory

**Comment by ghost** [comment]
TriggerEvent("qb-inventory:server:SaveStashItems

I've just seen it maybe you can include that in the config with I should be able to change yes simply had totally overread.

**Comment by ghost** [comment]
Actually, this should also work like this....

**Comment by ghost** [comment]
the event from qb-inventory is the same

**Comment by helenclarko** [comment]
Yeah, that qb-inventory call should be available on all the popular inventories (correct me if I am wrong). This is an issue with the info list not being assigned to your item, which I was not aware was going to be an issue. I'm using the info field to store which stash it is assigned to.

Hmmm, so it's trying to read the string value of the items info.stash.

If you could get it to print out "Player.PlayerData.items[item.slot].info" I could find out what is going on.
